config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  get "member/:id" => "welcome#show", as: "members_show"
  get "members/new" => "welcome#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :turbo_native_app?
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_data, except: [:new]
  def index

  end

  def new
    
  end

  def show
    @member = @data.find { |item| item[:id] == params[:id] }
    redirect_to root_path unless @member
  end

  def demo
    
  end
  private

  def set_data
    @data = [
      {
        id: "1",
        name: "Leslie Alexander",
        email: "leslie.alexander@example.com",
        role: "Co-Founder / CEO",
        active_at: "3h ago",
        image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      },
      {
        id: "2",
        name: "Michael Foster",
        email: "michael.foster@example.com",
        role: "Co-Founder / CTO",
        active_at: "3h ago",
        image: "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      },
      {
        id: "3",
        name: "Dries Vincent",
        email: "dries.vincent@example.com",
        role: "Business Relations",
        active_at: "Online",
        image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      },
      {
        id: "4",
        name: "Lindsay Walton",
        email: "lindsay.walton@example.com",
        role: "Front-end Developer",
        active_at: "3h ago",
        image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      },
      {
        id: "5",
        name: "Courtney Henry",
        email: "courtney.henry@example.com",
        role: "Designer",
        active_at: "3h ago",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      },
      {
        id: "6",
        name: "Tom Cook",
        email: "tom.cook@example.com",
        role: "Director of Product",
        active_at: "Online",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
      }
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_top_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Dashboard</a>
            <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
            <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
            <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <div>
            <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100 outline-none", Not Active: "" -->
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="#" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">Dashboard</a>
      <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
      <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
      <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=content_for(:title) || "Hotwire Native"%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-5 px-4 flex">
      <%#= render "/layouts/top_navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/welcome/demo.html.erb
<h1> No ios component page</h1>

app/views/welcome/index.html.erb
<% content_for :title, "Members"%>
<div class="w-full rounded overflow-hidden bg-white">
  <div class="flex justify-between items-center mb-2">
    <% if !turbo_native_app?%>
      <div class="text-xl font-bold text-gray-900">
        Members List
      </div>
    <% end %>
    <a href="<%=members_new_path%>" class="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-1 px-3 rounded">
      New Member
    </a>
  </div>
  <p class="text-gray-700 text-base">
    <ul role="list" class="divide-y divide-gray-100">
      <% @data.each do |member| %>
        <li class="flex w-full justify-between gap-x-6 py-5">
          <a href="<%=members_show_path(member.dig(:id))%>">
            <div class="flex min-w-0 gap-x-4">
              <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="<%=member.dig(:image)%>" alt="">
              <div class="min-w-0 flex-auto">
                <p class="text-sm/6 font-semibold text-gray-900"><%=member.dig(:name)%></p>
                <p class="mt-1 truncate text-xs/5 text-gray-500"><%=member.dig(:email)%></p>
              </div>
            </div>
            <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
              <p class="text-sm/6 text-gray-900"><%=member.dig(:role)%></p>
              <p class="mt-1 text-xs/5 text-gray-500">Last seen <%=member.dig(:active_at)%></p>
            </div>
          </a>
        </li>
      <% end %>
    </ul>
  </p>
</div>

app/views/welcome/new.html.erb
<% content_for :title, "New Member"%>
<form>
  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">
      <% if !turbo_native_app?%>
        <h2 class="text-base/7 font-semibold text-gray-900">Form Section</h2>
      <% end %>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

        <div class="col-span-full">
          <label for="photo" class="block text-sm/6 font-medium text-gray-900">Scanner</label>
          <div class="mt-2 flex items-center gap-x-3">
            <svg class="h-12 w-12 text-gray-300" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 297.497 297.497" xml:space="preserve">
            <g>
              <g id="XMLID_31_">
                <g>
                  <path style="fill:#99ABD5;" d="M244.297,147.048l-19.95,112.86c-0.47,2.66-2.77,4.6-5.48,4.6h-36.03c-2.25,0-3.64-1.25-4.26-1.99
                    c-0.62-0.74-1.61-2.32-1.21-4.54l7.51-42.5h15.92c5.74,0,10.4-4.66,10.4-10.4c0-5.73-4.66-10.39-10.4-10.39h-12.25l8.43-47.64
                    H244.297z"/>
                  <path style="fill:#99ABD5;" d="M276.467,57.508v44.24c0,13.52-11,24.51-24.52,24.51h-49.61l-37.3-93.27h86.91
                    C265.467,32.988,276.467,43.988,276.467,57.508z"/>
                  <polygon style="fill:#A38671;" points="142.647,32.988 179.957,126.258 157.037,126.258 119.727,32.988      "/>
                  <path d="M297.247,57.508v44.24c0,20.15-13.23,37.26-31.46,43.13l-20.97,118.65c-2.23,12.61-13.14,21.76-25.95,21.76h-36.03
                    c-7.81,0-15.16-3.43-20.18-9.42c-5.02-5.98-7.12-13.82-5.76-21.51l18.97-107.31h-25.87c-4.25,0-8.07-2.59-9.65-6.54
                    l-45.62-114.05c-1.28-3.2-0.89-6.83,1.04-9.68c1.94-2.86,5.16-4.57,8.61-4.57h147.57
                    C276.927,12.208,297.247,32.528,297.247,57.508z M276.467,101.748v-44.24c0-13.52-11-24.52-24.52-24.52h-86.91l37.3,93.27h49.61
                    C265.467,126.258,276.467,115.268,276.467,101.748z M224.347,259.908l19.95-112.86h-47.32l-8.43,47.64h12.25
                    c5.74,0,10.4,4.66,10.4,10.39c0,5.74-4.66,10.4-10.4,10.4h-15.92l-7.51,42.5c-0.4,2.22,0.59,3.8,1.21,4.54
                    c0.62,0.74,2.01,1.99,4.26,1.99h36.03C221.577,264.508,223.877,262.568,224.347,259.908z M179.957,126.258l-37.31-93.27h-22.92
                    l37.31,93.27H179.957z"/>
                  <path d="M90.197,121.488c5.29,2.24,7.76,8.34,5.53,13.62c-1.68,3.97-5.53,6.35-9.58,6.35c-1.35,0-2.72-0.26-4.04-0.82
                    c-13.78-5.83-24.47-16.67-30.09-30.54c-5.63-13.86-5.52-29.08,0.31-42.86c2.23-5.29,8.33-7.76,13.62-5.53
                    c5.28,2.23,7.76,8.33,5.52,13.62c-3.66,8.67-3.73,18.24-0.19,26.96C74.807,111.008,81.537,117.828,90.197,121.488z"/>
                  <path d="M71.647,165.388c5.29,2.23,7.76,8.33,5.53,13.62c-1.68,3.96-5.53,6.34-9.58,6.34c-1.35,0-2.72-0.26-4.04-0.82
                    c-52.65-22.26-77.38-83.2-55.13-135.85c2.24-5.28,8.33-7.76,13.62-5.52c5.29,2.23,7.76,8.33,5.53,13.61
                    C9.777,98.868,29.547,147.588,71.647,165.388z"/>
                </g>
                <g>
                </g>
              </g>
            </g>
            </svg>
            <a href="native://scanQRCode" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Scan code</a>

            <a href="<%= members_new_path(scan: 'code') %>" class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">Scan code 2</a>
          </div>
        </div>

        <div class="col-span-full">
          <label for="about" class="block text-sm/6 font-medium text-gray-900">Scanner data</label>
          <div class="mt-2">
            <input type="text" name="scan_id" id="scan-id" autocomplete="scan-id" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="col-span-full">
          <label for="cover-photo" class="block text-sm/6 font-medium text-gray-900">Cover photo</label>
          <div class="mt-2 flex justify-center rounded-lg border border-dashed border-gray-900/25 px-6 py-10">
            <div class="text-center">
              <svg class="mx-auto h-12 w-12 text-gray-300" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" data-slot="icon">
                <path fill-rule="evenodd" d="M1.5 6a2.25 2.25 0 0 1 2.25-2.25h16.5A2.25 2.25 0 0 1 22.5 6v12a2.25 2.25 0 0 1-2.25 2.25H3.75A2.25 2.25 0 0 1 1.5 18V6ZM3 16.06V18c0 .414.336.75.75.75h16.5A.75.75 0 0 0 21 18v-1.94l-2.69-2.689a1.5 1.5 0 0 0-2.12 0l-.88.879.97.97a.75.75 0 1 1-1.06 1.06l-5.16-5.159a1.5 1.5 0 0 0-2.12 0L3 16.061Zm10.125-7.81a1.125 1.125 0 1 1 2.25 0 1.125 1.125 0 0 1-2.25 0Z" clip-rule="evenodd" />
              </svg>
              <div class="mt-4 flex text-sm/6 text-gray-600">
                <label for="file-upload" class="relative cursor-pointer rounded-md bg-white font-semibold text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-600 focus-within:ring-offset-2 hover:text-indigo-500">
                  <span>Upload a file</span>
                  <input id="file-upload" name="file-upload" type="file" class="sr-only">
                </label>
                <p class="pl-1">or drag and drop</p>
              </div>
              <p class="text-xs/5 text-gray-600">PNG, JPG, GIF up to 10MB</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- <div class="border-b border-gray-900/10 pb-12">
      <h2 class="text-base/7 font-semibold text-gray-900">Personal Information</h2>
      <p class="mt-1 text-sm/6 text-gray-600">Use a permanent address where you can receive mail.</p>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label for="first-name" class="block text-sm/6 font-medium text-gray-900">First name</label>
          <div class="mt-2">
            <input type="text" name="first-name" id="first-name" autocomplete="given-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="last-name" class="block text-sm/6 font-medium text-gray-900">Last name</label>
          <div class="mt-2">
            <input type="text" name="last-name" id="last-name" autocomplete="family-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="sm:col-span-4">
          <label for="email" class="block text-sm/6 font-medium text-gray-900">Email address</label>
          <div class="mt-2">
            <input id="email" name="email" type="email" autocomplete="email" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="country" class="block text-sm/6 font-medium text-gray-900">Country</label>
          <div class="mt-2">
            <select id="country" name="country" autocomplete="country-name" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm/6">
              <option>United States</option>
              <option>Canada</option>
              <option>Mexico</option>
            </select>
          </div>
        </div>

        <div class="col-span-full">
          <label for="street-address" class="block text-sm/6 font-medium text-gray-900">Street address</label>
          <div class="mt-2">
            <input type="text" name="street-address" id="street-address" autocomplete="street-address" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="sm:col-span-2 sm:col-start-1">
          <label for="city" class="block text-sm/6 font-medium text-gray-900">City</label>
          <div class="mt-2">
            <input type="text" name="city" id="city" autocomplete="address-level2" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="region" class="block text-sm/6 font-medium text-gray-900">State / Province</label>
          <div class="mt-2">
            <input type="text" name="region" id="region" autocomplete="address-level1" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="postal-code" class="block text-sm/6 font-medium text-gray-900">ZIP / Postal code</label>
          <div class="mt-2">
            <input type="text" name="postal-code" id="postal-code" autocomplete="postal-code" class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6">
          </div>
        </div>
      </div>
    </div> -->
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <a href="<%=root_path%>" class="text-sm/6 font-semibold text-gray-900">Cancel</a>
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
  </div>
</form>

<script type="text/javascript">
    function scanQRCode() {
        window.location.href = "native://scanQRCode";
    }
</script>

app/views/welcome/show.html.erb
<% content_for :title, @member.dig(:name)%>
<p class="text-gray-700 text-base">
  <div class="block rounded-lg bg-white shadow-secondary-1 dark:bg-surface-dark">
    <a href="#!">
      <img class="rounded-t-lg" src="<%=@member.dig(:image)%>" alt=""/>
    </a>
    <div class="p-6 text-surface dark:text-white">
      <h5 class="mb-2 text-xl font-medium leading-tight"><%=@member.dig(:name)%></h5>
      <p class="mb-4 text-base">
        <%=@member.dig(:email)%>
        <p class="text-sm/6 text-gray-900"><%=@member.dig(:role)%></p>
        <p class="mt-1 text-xs/5 text-gray-500">Last seen <%=@member.dig(:active_at)%></p>
        <% if !turbo_native_app?%>
          <p class="text-sm/6 text-gray-900 pt-5">
            <a href="<%=root_path%>" class="bg-blue-500 hover:bg-blue-600 text-white py-1 px-3 rounded">
              Members List
            </a>
          </p>
        <% end %>
      </p>
    </div>
  </div>
</p>